// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/recipe-tag-links/$id')({
  component: RecipeTagLinksDetailPage,
})

function RecipeTagLinksDetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: recipe_tag_links */}
  return <div className="p-4">Loading recipe_tag_links detail...</div>
}
