// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/recipe-tag-links')({
  component: RecipeTagLinksListPage,
})

function RecipeTagLinksListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: recipe_tag_links */}
  return <div className="p-4">Loading recipe-tag-links...</div>
}
