/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by VibeStack — do not edit manually

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AboutImport } from './routes/about'
import { Route as ContactImport } from './routes/contact'
import { Route as RecipesListImport } from './routes/recipes/index'
import { Route as RecipesDetailImport } from './routes/recipes/$id'
import { Route as RecipeIngredientsListImport } from './routes/recipe-ingredients/index'
import { Route as RecipeIngredientsDetailImport } from './routes/recipe-ingredients/$id'
import { Route as RecipeTagsListImport } from './routes/recipe-tags/index'
import { Route as RecipeTagsDetailImport } from './routes/recipe-tags/$id'
import { Route as RecipeTagLinksListImport } from './routes/recipe-tag-links/index'
import { Route as RecipeTagLinksDetailImport } from './routes/recipe-tag-links/$id'

const IndexRoute = IndexImport.update({ id: '/', path: '/', getParentRoute: () => rootRoute } as any)
const AboutRoute = AboutImport.update({ path: '/about', getParentRoute: () => rootRoute } as any)
const ContactRoute = ContactImport.update({ path: '/contact', getParentRoute: () => rootRoute } as any)

const RecipesListRoute = RecipesListImport.update({ path: '/recipes/', getParentRoute: () => rootRoute } as any)
const RecipesDetailRoute = RecipesDetailImport.update({ path: '/recipes/$id', getParentRoute: () => rootRoute } as any)
const RecipeIngredientsListRoute = RecipeIngredientsListImport.update({ path: '/recipe-ingredients/', getParentRoute: () => rootRoute } as any)
const RecipeIngredientsDetailRoute = RecipeIngredientsDetailImport.update({ path: '/recipe-ingredients/$id', getParentRoute: () => rootRoute } as any)
const RecipeTagsListRoute = RecipeTagsListImport.update({ path: '/recipe-tags/', getParentRoute: () => rootRoute } as any)
const RecipeTagsDetailRoute = RecipeTagsDetailImport.update({ path: '/recipe-tags/$id', getParentRoute: () => rootRoute } as any)
const RecipeTagLinksListRoute = RecipeTagLinksListImport.update({ path: '/recipe-tag-links/', getParentRoute: () => rootRoute } as any)
const RecipeTagLinksDetailRoute = RecipeTagLinksDetailImport.update({ path: '/recipe-tag-links/$id', getParentRoute: () => rootRoute } as any)

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  ContactRoute,
  RecipesListRoute,
  RecipesDetailRoute,
  RecipeIngredientsListRoute,
  RecipeIngredientsDetailRoute,
  RecipeTagsListRoute,
  RecipeTagsDetailRoute,
  RecipeTagLinksListRoute,
  RecipeTagLinksDetailRoute,
])
